### ISSUE TITLE
Install and configure rabbitmq

### ISSUE THREAD

**Issue by wamberg** [zepheira/chef-viewshare#1]
Hi @dfeeney,

Would you like me to start a branch that installs and configures rabbitmq for viewshare? The [opscode rabbitmq cookbook](https://github.com/opscode-cookbooks/rabbitmq) looks like a good place to start. My initial plan would be to alter our [viewshare recipe](https://github.com/zepheira/chef-viewshare/blob/master/recipes/default.rb) to create a rabbitmq user and vhost for viewshare. I'd also change our [django settings template](https://github.com/zepheira/chef-viewshare/blob/master/templates/default/settings.py.erb) to include celery variables.  I know that the asynchronous transformation branch is still being developed. I don't mean to put the cart before the horse but I wanted to start talking about the infrastructure changes we have coming up.

Thanks, Bill

**Comment by dfeeney** [comment]
Yes, please do.  I think that the application_python cookbook provides some facility for configuring celery, but I'm not sure about the set up of rabbitmq.
